import test from 'node:test';import assert from 'node:assert/strict';
import {verifyTransition,runReserved,boundedPublicInput} from './daily-runner.mjs';
import {prepareDailyRequest,operationId} from './daily-controller.mjs';
import {evidence} from './prepare.mjs';
const now=new Date('2026-10-05T01:00:00Z'),empty={version:1,days:[],request:null};
test('replaying a reserved manifest on a later code commit fails',()=>{const l=prepareDailyRequest(empty,{operationId:operationId('run','site'),kind:'long',now});assert.equal(verifyTransition(empty,l,now).reservedCalls,2);assert.throws(()=>verifyTransition(l,l,now),/DUPLICATE/);});
test('public evidence input bounded and credential URLs refused',()=>{assert.throws(()=>boundedPublicInput({topic:'a',evidence:[{url:'https://user:password@example.com/',facts:[]}]}),/INVALID_PUBLIC/);assert.throws(()=>boundedPublicInput({topic:'a',evidence:[{url:'https://example.com/?token=x',facts:[]}]}),/INVALID_PUBLIC/);});
function response(text){const f={model:'grok-4.6-build',status:'completed',usage:{input_tokens:10,output_tokens:10},output:[{type:'message',content:[{type:'output_text',text}]}]};return {ok:true,status:200,text:async()=>[...Array.from(text).map(delta=>({type:'response.output_text.delta',delta})),{type:'response.completed',response:f}].map(x=>'data: '+JSON.stringify(x)+'\n\n').join('')};}
test('998 characters get one bounded append, not a network retry',async()=>{let calls=0;const result=await runReserved({kind:'long',reservedCalls:2},'fixture-key',{transport:async()=>response('文'.repeat(++calls===1?998:350)+evidence.map(x=>x.url).join(' ')),wait:async()=>assert.fail('not transient')});assert.equal(calls,2);assert.equal(result.supplemented,true);assert.equal(result.chineseCharacters,1348);assert.equal(result.status,'completed');});
test('transient failure retries once after waiting and retains two slots',async()=>{let calls=0,waits=0;const result=await runReserved({kind:'long',reservedCalls:2},'fixture-key',{transport:async()=>{calls++;return {ok:false,status:502,text:async()=>'{}'};},wait:async ms=>{assert.equal(ms,20000);waits++;}});assert.equal(calls,2);assert.equal(waits,1);assert.equal(result.status,'needs_review');});
test('undersized append stops at two calls',async()=>{let calls=0;const result=await runReserved({kind:'long',reservedCalls:2},'fixture-key',{transport:async()=>{calls++;return response('文'.repeat(100));}});assert.equal(calls,2);assert.equal(result.status,'needs_review');});
test('other public sites use the same quota and exact approved web sources',async()=>{const url='https://nodejs.org/en/about',input={topic:'Node.js',evidence:[{url,facts:['Public official source.']}]};let calls=0;const result=await runReserved({kind:'web',reservedCalls:1,publicInput:input},'fixture-key',{transport:async(_,options)=>{calls++;const b=JSON.parse(options.body);assert.deepEqual(b.tools[0].filters.allowed_domains,['nodejs.org']);assert.equal(b.max_turns,1);const text='官方来源 '+url,f={model:'grok-4.6-build',status:'completed',usage:{input_tokens:10,output_tokens:10,num_server_side_tools_used:1},output:[{type:'web_search_call',status:'completed',action:{sources:[{url}]}},{type:'message',content:[{type:'output_text',text}]}]};return {ok:true,status:200,text:async()=>'data: '+JSON.stringify({type:'response.output_text.delta',delta:text})+'\n\ndata: '+JSON.stringify({type:'response.completed',response:f})+'\n\n'};}});assert.equal(calls,1);assert.equal(result.status,'completed');assert.deepEqual(result.results[0].sources,[url]);});
