import test from 'node:test';import assert from 'node:assert/strict';import {GLOBAL_LEDGER,beijingDay,guardedCall,reserve,settle} from './grok-daily-budget-gate.mjs';
// Serialized memory store is a test double, not production shared persistence.
function fixture(){const data=new Map();let tail=Promise.resolve();const store={transaction(fn){const next=tail.then(()=>fn({get:async k=>structuredClone(data.get(k)),put:async(k,v)=>data.set(k,structuredClone(v))}));tail=next.catch(()=>{});return next;}};return {ledgerNamespace:GLOBAL_LEDGER,atomicStore:store,billingBoundsVerified:true};}
const attempt=(siteId,id,usd)=>({siteId,operationId:id,hardMaximumUsd:usd,allChargesBounded:true,now:new Date('2026-10-04T03:00:00Z')});
test('date changes at Beijing midnight',()=>{assert.equal(beijingDay(new Date('2026-10-03T15:59:59Z')),'2026-10-03');assert.equal(beijingDay(new Date('2026-10-03T16:00:00Z')),'2026-10-04');});
test('missing shared ledger or full bounds causes zero calls',async()=>{let calls=0;await assert.rejects(guardedCall({},attempt('a','one',1),async()=>calls++),/UNCONFIGURED/);const c=fixture();c.billingBoundsVerified=false;await assert.rejects(guardedCall(c,attempt('a','two',1),async()=>calls++),/UNVERIFIED/);assert.equal(calls,0);});
test('parallel sites share one global ceiling',async()=>{const c=fixture();let calls=0;const result=await Promise.allSettled([guardedCall(c,attempt('site-a','a',60),async()=>calls++),guardedCall(c,attempt('site-b','b',60),async()=>calls++)]);assert.equal(result.filter(x=>x.status==='fulfilled').length,1);assert.equal(calls,1);});
test('failed unknown cost holds reserve and duplicates never call again',async()=>{const c=fixture();let calls=0;await assert.rejects(guardedCall(c,attempt('a','one',70),async()=>{calls++;throw Error('transport');}),/RESERVE_RETAINED/);await assert.rejects(guardedCall(c,attempt('a','one',70),async()=>calls++),/DUPLICATE/);await assert.rejects(reserve(c,attempt('b','retry',40)),/EXCEEDED/);assert.equal(calls,1);});
test('verified settlement only releases actual unused reserve',async()=>{const c=fixture(),r=await reserve(c,attempt('a','one',70));assert.equal((await settle(c,r,{verifiedTotalUsd:0,invoiceOrUsagePricingVerified:false})).status,'reserve_retained');await settle(c,r,{verifiedTotalUsd:30,invoiceOrUsagePricingVerified:true});await reserve(c,attempt('b','two',70));await assert.rejects(reserve(c,attempt('a','three',.000001)),/EXCEEDED/);});
