import test from 'node:test';
import assert from 'node:assert/strict';
import { MODEL,grokMaximum,grokBody,parseGrok,execute } from './grok-nonreason-once.mjs';
import { prompt } from './run-once.mjs';
const response={model:MODEL,status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Synthetic public tutorial'}]}],usage:{input_tokens:501,output_tokens:600,output_tokens_details:{reasoning_tokens:0}}};
test('same prompt and bounded non-reasoning request excludes paid tools',()=>{const body=grokBody(prompt());assert.equal(body.input,prompt());assert.equal(body.max_output_tokens,1200);assert.deepEqual(body.tools,[]);assert.equal(body.tool_choice,'none');assert.equal(body.store,false);assert.ok(grokMaximum(prompt())<0.04);});
test('unexpected reasoning, model routing, over-limit tokens and tools stop',()=>{assert.throws(()=>parseGrok({...response,model:'grok-4.6'},prompt(),'synthetic'),/MISMATCH/);assert.throws(()=>parseGrok({...response,usage:{...response.usage,output_tokens_details:{reasoning_tokens:1}}},prompt(),'synthetic'),/BOUND/);assert.throws(()=>parseGrok({...response,usage:{...response.usage,output_tokens:1201}},prompt(),'synthetic'),/BOUND/);assert.throws(()=>parseGrok({...response,usage:{...response.usage,num_server_side_tools_used:1}},prompt(),'synthetic'),/TOOLS/);});
test('model not listed and auth refusal cause zero inference requests',async()=>{for(const meta of [{ok:false,status:401},{ok:true,text:async()=>JSON.stringify({data:[{id:'grok-4.6'}]})}]){let calls=0;const r=await execute('synthetic',async()=>{calls++;return meta;});assert.equal(calls,1);assert.equal(r.grok.requests,0);}});
test('one metadata GET and one inference POST; no automatic retries',async()=>{let calls=0;const r=await execute('synthetic',async(url,options)=>{calls++;if(options.method==='GET')return {ok:true,text:async()=>JSON.stringify({data:[{id:MODEL}]})};return {ok:true,text:async()=>JSON.stringify(response)};});assert.equal(calls,2);assert.equal(r.grok.status,'responded');assert.equal(r.grok.usage.reasoningTokens,0);assert.equal(r.grok.estimatedRelayCostUsd,0.000637875);});
