import test from 'node:test';
import assert from 'node:assert/strict';
import { prompt, worstCost, requestBody, safeText, parseClaude, claudeOnce, catalogueOnce } from './run-once.mjs';
const result = { type: 'message', model: 'claude-sonnet-5', content: [{type:'text',text:'Synthetic public tutorial'}], usage: { input_tokens: 100, output_tokens: 200 }, stop_reason: 'end_turn' };
test('bounded request reserves total budget and forbids tools/thinking', () => { assert.ok(worstCost(prompt()) < 0.15); assert.equal(requestBody(prompt()).max_tokens,1200); assert.deepEqual(requestBody(prompt()).tools,[]); assert.deepEqual(requestBody(prompt()).thinking,{type:'disabled'}); assert.throws(()=>worstCost('a'.repeat(6001)),/BOUND/); });
test('one request only, errors never retried or printed', async () => { let requests=0; const fetcher=async ()=>{requests++;return {ok:false,status:400};}; const r=await claudeOnce('synthetic-credential',fetcher); assert.equal(requests,1); assert.equal(r.httpStatus,400); });
test('only allowlisted response fields retained and usage cost derived', () => { const parsed=parseClaude({...result,account:'private-field'},prompt()); assert.ok(!JSON.stringify(parsed).includes('private-field')); assert.equal(parsed.estimatedCostAtMaxGroupUsd,0.00462); assert.throws(()=>parseClaude({...result,model:'unknown'},prompt()),/MISMATCH/); assert.throws(()=>parseClaude({...result,usage:{input_tokens:100,output_tokens:1201}},prompt()),/LIMIT/); assert.throws(()=>parseClaude({...result,content:[{type:'tool_use'}]},prompt()),/CONTENT/); });
test('sensitive outputs rejected before logging or retention', () => { for(const text of ['synthetic-credential','authorization: value','123.45.67.89','user@example.com']) assert.throws(()=>safeText(text,['synthetic-credential']),/UNSAFE/); });
test('catalog is read-only and contains no account or ownership fields', async()=> { let method;const r=await catalogueOnce('synthetic-credential',async(url,opts)=>{method=opts.method;return {ok:true,text:async()=>JSON.stringify({data:[{id:'grok-4.6',owned_by:'private'},{id:'grok-imagine-image',account:'private'},{id:'account-secret'}]})};}); assert.equal(method,'GET'); assert.deepEqual(r.imageModelIds,['grok-imagine-image']); assert.ok(!JSON.stringify(r).includes('private')); });
